spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analysislist?currentSchema=analysislist
    username: test123
    password: test123
    driver-class-name: org.postgresql.Driver
liquibase:
  change-log: classpath:liquibase/db.changelog.yaml
  enabled: true
  default-schema: analysislist
sql:
  init:
    mode: never
    continue-on-error: false
    data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: Z3Jlc2dlIHJzZ3NyZCBzcmdzZ3NnZGRzZ2RzZ2Rz
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false